name: test coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          make install
          make build
      - name: Start inner project linter
        run: |
          make lint
